before:
  hooks:
    - go mod tidy
builds:
  -
    main: ./
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  groups:
  - title: Features
    regexp: "^feat:\\s.+$"
    order: 0
  - title: Bug fixes
    regexp: "^fix:\\s.+$"
    order: 1
  - title: Others
    order: 999
  filters:
    exclude:
      - "^docs:\\s.+"
      - "^test:\\s.+"
brews:
  -
    # Name template of the recipe
    # Default to project name
    name: note-cli

    # Github repository to push the tap to.
    tap:
      owner: KatsuyaAkasaka
      name: homebrew-tap

      # Optionally a branch can be provided.
      # Defaults to the default repository branch.
      branch: main

    # Template for the url which is determined by the given Token (github or gitlab)
    # Default for github is "https://github.com/<repo_owner>/<repo_name>/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    # Default for gitlab is "https://gitlab.com/<repo_owner>/<repo_name>/uploads/{{ .ArtifactUploadHash }}/{{ .ArtifactName }}"
    url_template: "https://github.com/KatsuyaAkasaka/note-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/KatsuyaAkasaka"

    # Your app's description.
    # Default is empty.
    description: "note-cli"

    # Custom install script for brew.
    # Default is 'bin.install "program"'.
    install: |
      bin.install "note-cli"
